### ISSUE TITLE
add in-script navigation 

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-script-builder#21]
@akariv as a first exercise, let's add:

1. a quick jump link, from any goto block:

![image](https://user-images.githubusercontent.com/3581741/75090579-eaa91580-556c-11ea-8fd5-3058963e8b9d.png)

2. Ofer already implemented a referral 'back' link on each block, but instead of showing the concrete referring snippet name, the label shows the type of the referring block:

![image](https://user-images.githubusercontent.com/3581741/75090649-a36f5480-556d-11ea-8abf-a9d0fdb4900b.png)

![image](https://user-images.githubusercontent.com/3581741/75090683-05c85500-556e-11ea-8596-f72f5477ba49.png)

Please fix the label to "referring from: [snippet name]" 

3. Split "Infocards", "Organizations", "Task Templates" content (and editing) into separate tabs:

![image](https://user-images.githubusercontent.com/3581741/75092287-cc4c1580-557e-11ea-8127-3b0bd241fcd2.png)

4. a side navigator, listing all snippets with a color indicator for the active/on focus snippet (will be handled seprately on https://github.com/hasadna/reportit-script-builder/issues/23).

**Comment by noamoss** [comment]
@akariv added relevant visual examples

**Comment by akariv** [comment]
can we open an issues for each of these separate issues?

**Comment by noamoss** [comment]
@akariv 

> a quick jump link, from any goto block

https://github.com/hasadna/reportit-script-builder/issues/27

> Please fix the label to "referring from: [snippet name]" 

https://github.com/hasadna/reportit-script-builder/issues/28

> Split "Infocards", "Organizations", "Task Templates" content (and editing) into separate tabs

https://github.com/hasadna/reportit-script-builder/issues/29


closing this issue.
